export const Component = {
  RestApplication: Symbol('RestApplication'),
  Logger: Symbol('Logger'),
  Config: Symbol('Config'),
  DatabaseClient: Symbol('DatabaseClient'),
  UserService: Symbol('UserService'),
  UserModel: Symbol('UserModel'),
  UserController: Symbol('UserController'),
  OfferService: Symbol('OfferService'),
  OfferModel: Symbol('OfferModel'),
  OfferController: Symbol('OfferController'),
  CommentService: Symbol('CommentService'),
  CommentModel: Symbol('CommentModel'),
  CommentController: Symbol('CommentController'),
  AppExceptionFilter: Symbol('AppExceptionFilter'),
  AuthService: Symbol('AuthService'),
  AuthExceptionFilter: Symbol('AuthExceptionFilter'),
  HttpErrorExceptionFilter: Symbol('HttpErrorExceptionFilter'),
  ValidationExceptionFilter: Symbol('ValidationExceptionFilter'),
  PathTransformer: Symbol('PathTransformer'),
} as const;
