# Comments
## Get comments

GET http://localhost:4000/comments HTTP/1.1
Content-Type: application/json

###

## Create comment

POST http://localhost:4000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayBTcGFycm93IiwidXNlclR5cGUiOiJzdGFuZGFyZCIsImlkIjoiNjdlNTFlODVjZGRjZWU5ZmYzNDc2NTJhIiwiaWF0IjoxNzQzNTkyNzY5LCJleHAiOjE3NDM3NjU1Njl9.Tetvet_qCDtMu6FzDceb4DojI_tXTv1twvQ7kJqjgE0

{
  "text": "test 2",
  "offerId": "67e665c274cf178952b36ea7",
  "authorId": "67e51e85cddcee9ff347652a",
  "rating": 1
}

###
