# Comments
## Get comments

GET http://localhost:4000/comments HTTP/1.1
Content-Type: application/json

###

## Create comment

POST http://localhost:4000/comments HTTP/1.1
Content-Type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwibmFtZSI6IkphY2sgU3BhcnJvdyIsInVzZXJUeXBlIjoic3RhbmRhcmQiLCJpZCI6IjY3ZWUzNzRmNmM1ZGU4Mzc5YWZmMzljZiIsImlhdCI6MTc0MzY2NTI5MSwiZXhwIjoxNzQzODM4MDkxfQ.7iEgCn7l-CkPzlyyKEgy_HfuWcE2-kcZtkvfmr6TM1c

{
  "text": "test 6",
  "offerId": "67ee37fa6c5de8379aff39df",
  "userId": "67ee374f6c5de8379aff39cf",
  "rating": 1
}

###
